### PR TITLE
requery_hier may not find a segment in the level / attribute its been…

### PR DESCRIPTION
**Pull request by FredrikKarlssonSpeech**
… asked to look, and will return lines with all NAs in them.

This fix will allow for segmentlists of type event and NA to be created, and somehow fixes Issue #216

### CODE REVIEW

**Comment by raphywink** [comment]
Sorry but I am really pressed 4 time in the next few weeks with ICPhS looming. I will have a look at this after the conference. However, one thing I can already say is that your changes don't seem to pass the our checks/unit tests.

**Comment by FredrikKarlssonSpeech** [comment]
No problem. I will have a look at the travis logs and see what could be a problem.

**Comment by FredrikKarlssonSpeech** [comment]
I need guidance on what you see as the desired behaviour within the framework. 
Perhaps it is not the issue that makes your tests complain, but I still need to make sure I understand what is wanted here before I look into the solution.

If you to a hierarchical requery on a set of parent segments where for some there will be a cild item and for some there will not be. (Not every word has a [k] transcribed for it at a child level).
What is then the desired behaviour? I have viewed it as a left join of the parent items and the child items. That is, there will be the same number of rows in the output segment list as in the segmentlist that is supplied to the requery function, and they will be ordered the same way of course. This will create lots of NA rows though, as there will sometimes be no matching child item.
Allowing NAs was basically how I fixed the problem I was seeing in requery_hier.

If you don't allow NA rows then you essentially have a right / full join situation, where only rows that did have an item on the child level is included. Then you dont have to handle the NA row case, but you will have no simple way of linking what went into the requery function and what came out of it. 
Unless you make sure that there is a hidden reference to the segments in the original query list.

**Comment by raphywink** [comment]
see d2895b8 commit.

**Pull request closed without merging**
